#ifndef OVERRIDE_RTEMS_ATTR_H
#define OVERRIDE_RTEMS_ATTR_H

#include "OCS_rtems_attr.h"

#define RTEMS_SIMPLE_BINARY_SEMAPHORE OCS_RTEMS_SIMPLE_BINARY_SEMAPHORE
#define RTEMS_PRIORITY OCS_RTEMS_PRIORITY

#endif
